# Generated by Django 3.1.7 on 2021-03-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from_bac', models.SmallIntegerField(default=0, help_text='year since the bac', verbose_name='year')),
                ('scholar_year', models.CharField(default='0000-0001', max_length=9, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='comment on student', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='???', help_text='last name of student', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(default='x@y.z', help_text='email of student', max_length=255, verbose_name='email of student'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='099999999', help_text='phone number of student', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='cursus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.cursus'),
        ),
    ]
