# Generated by Django 3.1.5 on 2021-03-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_auto_20210316_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursus',
            name='year_from_bac',
        ),
    ]
