# Generated by Django 3.1.5 on 2021-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_remove_cursus_year_from_bac'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='name',
            field=models.CharField(default='aucun', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cursus',
            name='year_from_bac',
            field=models.SmallIntegerField(default=0, help_text='year since the bac', verbose_name='year'),
        ),
    ]
